title: Moylan Law LLC
email: Constance@Moylan-Law.com
description: >- 
  Sophisticated, global perspective to the sensitive world of estates and legacy.
baseurl: "moylan-law-website"
url: "https://www.moylan-law.com"
theme: minima